import Head from 'next/head'
import Navbar from '../components/navbar/Navbar'
import Search from '../components/Search'
import Place from '../components/place/Places'
import Container from '../components/Container'
export default function Home() {
  return (
    <>
      <Head>
        <title>Airwo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Container/>
       <main className='flex min-h-[calc(100vh-100px)] flex-col items-center'>


      </main>
    </>
  )
}
