import Head from 'next/head'
import Places from '../components/place/Places'
import Layout from '../components/Layout'
import WelcomeMessage from '../components/Welcome'
export default function Home() {
  return (
    <>
      <Head>
        <title>AirAl</title>
        
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6301474212380306"
     crossorigin="anonymous"></script>
      </Head>
      <Layout >
        <WelcomeMessage/>
        <Places/>
      </Layout>
    </>
  )
}
