import Head from 'next/head'
import { useState } from 'react'
import Places from '../components/place/Places'
import Layout from '../components/Layout'
import WelcomeMessage from '../components/Welcome'
import HeroBanner from '../components/home/HeroBanner'

export default function Home() {
  const [searchValue, setSearchValue] = useState("");

  return (
    <>
      <Head>
        <title>AirAl</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <WelcomeMessage/>
        <HeroBanner onSearch={setSearchValue} />
        <Places searchValue={searchValue} />
      </Layout>
    </>
  )
}
